create table logs (
	`Number` text,
	`Date` text,
	`Time` text,
	`Interface` text,
	`Origin` text,
	`Type` text,
	`Action` text,
	`Service` text,
	`Source Port` text,
	`Source` text,
	`Destination` text,
	`Protocol` text,
	`Rule` text,
	`Rule Name` text,
	`Current Rule Number` text,
	`User` text,
	`Information` text,
	`Product` text,
	`Source Machine Name` text,
	`Source User Name`
)
